# Generated by Django 2.1.4 on 2019-02-23 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import workOrder.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='工单标题')),
                ('o_type', models.SmallIntegerField(choices=[(0, '规划设计'), (1, '集成实施-硬件'), (2, '集成实施-网络'), (3, '集成实施-服务器'), (4, '集成实施-软件'), (5, '入网交维-安全加固'), (6, '入网交维-入网提交')], default=0, verbose_name='工单类型')),
                ('o_state', models.SmallIntegerField(choices=[(0, '已保存'), (1, '待审批'), (2, '审批通过-待接单'), (3, '待执行'), (4, '待重审'), (5, '待确认完成'), (6, '已完成'), (7, '驳回申请')], verbose_name='工单状态')),
                ('deadLine', models.DateTimeField(verbose_name='截止日期')),
                ('project', models.CharField(max_length=64, verbose_name='所属项目')),
                ('content', models.TextField(verbose_name='工单内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=workOrder.models.attachment_directory_path, verbose_name='附件')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approver', to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
                ('executor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executor', to=settings.AUTH_USER_MODEL, verbose_name='执行人')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-c_time'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderNum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=64, verbose_name='工单号')),
                ('c_time', models.DateTimeField(auto_now_add=True, verbose_name='工单发起日期')),
            ],
            options={
                'verbose_name': '工单号',
                'verbose_name_plural': '工单号',
                'ordering': ['-c_time'],
            },
        ),
        migrations.AddField(
            model_name='workorder',
            name='workOrder_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workOrder.WorkOrderNum', verbose_name='工单号'),
        ),
    ]
