# Generated by Django 2.1.4 on 2019-02-23 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='描述'),
        ),
    ]
